export {
  getTelegramClient,
  getClientVersion,
  isClientReady,
  waitForClientReady,
  setClientReady,
  isAuthenticated,
  getCurrentUser,
  logout,
  resetClient,
  setLogLevel,
  getLogLevel,
  LogLevel,
  getIsOnline,
  onNetworkOnline,
  type LogLevelType,
} from './client'
export {
  startPhoneAuth,
  submitCode,
  submit2FA,
  startQRAuth,
  stopQRAuth,
  type AuthState,
  type AuthCallbacks,
} from './auth'
export {
  fetchChannels,
  fetchChannelsWithLastMessages,
  getChannel,
  getChannelFullInfo,
  joinChannel,
  leaveChannel,
  type Channel,
  type ChannelWithLastMessage,
  type ChannelFullInfo,
  type ChannelsWithPostsResult,
} from './channels'
export {
  fetchMessages,
  getMessage,
  mapMessage,
  sendReaction,
  getAvailableReactions,
  sliceWithCompleteGroups,
  type Message,
  type MessageMedia,
  type MessageEntity,
  type MessageReaction,
  type FetchMessagesOptions,
  type PhotoMedia,
  type VideoMedia,
  type VideoNoteMedia,
  type AnimationMedia,
  type DocumentMedia,
  type AudioMedia,
  type VoiceMedia,
  type StickerMedia,
  type LocationMedia,
  type VenueMedia,
  type PollMedia,
  type ContactMedia,
  type DiceMedia,
  type WebpageMedia,
  type MediaOfType,
  type MessageMediaStrict,
} from './messages'
export {
  fetchComments,
  sendComment,
  hasCommentsEnabled,
  loadAuthorPhoto,
  CommentError,
  type Comment,
  type CommentAuthor,
  type CommentReaction,
  type CommentThread,
  type FetchCommentsOptions,
} from './comments'
export {
  downloadMedia,
  downloadProfilePhoto,
  getVideoStreamUrl,
  preloadThumbnails,
  clearMediaCache,
  getCachedMedia,
  removeFromMediaCache,
  getMediaCacheStats,
  cleanupExpiredCache,
} from './media'
// MTProto error handling utilities
export {
  // Type guards for specific errors
  isRpcError,
  isFloodWait,
  isChannelInvalid,
  isMessageNotFound,
  is2FARequired,
  isInvalidPhoneCode,
  isInvalidPassword,
  isSignUpRequired,
  isFileReferenceExpired,
  isUserDeactivated,
  isPeerNotFound,
  isIgnorableError,
  // Error utilities
  categorizeError,
  getErrorMessage,
  withFloodWaitRetry,
  logIfNotIgnorable,
  // Constants
  FLOOD_WAIT_THRESHOLD,
  MAX_FLOOD_WAIT,
  // Types
  type ErrorCategory,
} from './errors'
export {
  startUpdatesListener,
  stopUpdatesListener,
  isUpdatesListenerActive,
  onTimelineLoaded,
  type UpdatesCleanup,
} from './updates'
export {
  openChannel,
  closeChannel,
  closeAllChannels,
  updateOpenChannels,
  getOpenChannels,
  isChannelOpen,
  getOpenChatsStats,
} from './openChats'
export {
  subscribeToComments,
  onCommentUpdate,
  getActiveSubscriptionCount,
  type CommentSubscription,
  type CommentUpdate,
  type CommentUpdateCallback,
} from './commentUpdates'
